import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

// const inter = Inter({ subsets: ["latin"] });
const cabinetRegular = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Regular.otf",
  variable: "--cabinet-regular",
});
const cabinetBold = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Bold.otf",
  variable: "--cabinet-bold",
});
// const cabinetExtrabold = localFont({src: "../public/fonts/cabinet/CabinetGrotesk-Extrabold.otf", variable: "--cabinet-extrabold"})
const cabinetLight = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Light.otf",
  variable: "--cabinet-light",
});
// const cabinetExtraLight =localFont({src: "../public/fonts/cabinet/CabinetGrotesk-Extralight.otf", variable: "--cabinet-extralight"})
const cabinetMedium = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Medium.otf",
  variable: "--cabinet-medium",
});
const cabinetThin = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Thin.otf",
  variable: "--cabinet-thin",
});
const cabinetBlack = localFont({
  src: "../public/fonts/cabinet/CabinetGrotesk-Black.otf",
  variable: "--cabinet-black",
});
const generalSansRegular = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Regular.otf",
  variable: "--generalsans-regular",
});
const generalSansBold = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Bold.otf",
  variable: "--generalsans-bold",
});
const generalSansItalic = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Italic.otf",
  variable: "--generalsans-italic",
});
const generalSansSemiBold = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Semibold.otf",
  variable: "--generalsans-semibold",
});
const generalSansMedium = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Semibold.otf",
  variable: "--generalsans-medium",
});
const generalSansLight = localFont({
  src: "../public/fonts/general_sans/GeneralSans-Light.otf",
  variable: "--generalsans-light",
});
const generalSansVariable = localFont({
  src: "../public/fonts/general_sans/variable/GeneralSans-Variable.ttf",
  variable: "--generalsans-variable",
});
const tanker = localFont({
  src: "../public/fonts/Tanker-Regular.otf",
  variable: "--tanker",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetRegular.className} ${cabinetBlack.variable} ${cabinetThin.variable}
         ${cabinetBold.variable} ${cabinetMedium.variable} ${generalSansRegular.variable}
         ${generalSansBold.variable} ${cabinetLight.variable} ${generalSansItalic.variable} 
         ${generalSansSemiBold.variable} ${generalSansMedium.variable} ${generalSansLight.variable} 
         ${generalSansVariable.variable} ${tanker.variable} overflow-hidden overflow-y-auto bg-off-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
